# Generated by Django 4.2.3 on 2023-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("APPLE", "APPLE"),
                            ("SAMSUNG", "SAMSUNG"),
                            ("HUAWEI", "HUAWEI"),
                            ("ASUS", "ASUS"),
                            ("LENOVO", "LENOVO"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year_of_manufacture", models.SmallIntegerField()),
                ("memory_size", models.IntegerField()),
                ("hard_disk_size", models.IntegerField()),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField(default=0)),
                ("date_is_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
